name: "Reolink NVR Dashboard"
description: "Dashboard per NVR Reolink con live view telecamere e gestione registrazioni"
version: "1.0.4"
slug: "reolink_nvr_dashboard"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - data:rw
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: "Web Dashboard NVR Reolink"
ingress: true
ingress_port: 3000
panel_icon: "mdi:cctv"
panel_title: "NVR Reolink"
