name: "Reolink NVR Dashboard"
description: "Dashboard per NVR Reolink con live view telecamere e gestione registrazioni"
version: "1.1.2"
slug: "reolink_nvr2"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress: true
ingress_port: 3000
panel_icon: mdi:cctv
homeassistant_api: false
map:
  - data:rw
